### ISSUE TITLE
Positions method

### ISSUE THREAD

**Issue by cynanrhodes** [rviney/ig_markets#2]
Thanks for your work on this gem.

In running the request for positions, using:

ig = IGMarkets::DealingPlatform.new
ig.sign_in 'username', 'password', 'api_key', :demo
puts ig.positions.inspect

for me, this produces the error below.  The IG session is authenticated and plenty of the other methods (accounts, activity, transactions etc) all work well and the error seems limit to positions.

ArgumentError: Unknown attributes: update_time_ut_c
from /User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-315415946ae8/lib/ig_markets/model.rb:15:in `initialize'
from /User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-315415946ae8/lib/ig_markets/model.rb:48:in `new'
from /User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-315415946ae8/lib/ig_markets/model.rb:48:in `from'
from /User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-315415946ae8/lib/ig_markets/model.rb:70:in `block in define_attribute_writer'
from /User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-315415946ae8/lib/ig_markets/model.rb:74:in `call'
from /User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-315415946ae8/lib/ig_markets/model.rb:74:in `block in define_attribute_writer'
from /User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-315415946ae8/lib/ig_markets/model.rb:11:in `block in initialize'
from /User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-315415946ae8/lib/ig_markets/model.rb:10:in `each'
from /User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-315415946ae8/lib/ig_markets/model.rb:10:in `initialize'
from /User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-315415946ae8/lib/ig_markets/dealing_platform.rb:65:in `new'
from /User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-315415946ae8/lib/ig_markets/dealing_platform.rb:65:in `block in positions'
from /User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-315415946ae8/lib/ig_markets/dealing_platform.rb:64:in `map'
from /User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-315415946ae8/lib/ig_markets/dealing_platform.rb:64:in `positions'

thanks

**Comment by rviney** [comment]
Thanks, IG added an extra attribute to the API. fixed in f4cd575.
