### ISSUE TITLE
Use pageSize and pageNumber when fetching large numbers of activities and transactions

### ISSUE THREAD

**Issue by richard-viney** [rviney/ig_markets#8]
There are `pageSize` and `pageNumber` options on V2 of `/history/activities` and `/history/transactions`.

These should be able to be used to simplify the history request methods implemented in `IGMarkets::DealingPlatform::AccountMethods`, so that they no longer need to manually update `to=` on the URL when fetching more than 500 records at once.

See: https://labs.ig.com/rest-trading-api-reference/service-detail?id=525

**Comment by Aflier** [comment]
If this is related to:

`market.historical_prices resolution: :second, from: Time.now - 120, to: Time.now - 60`

It would be great to be able to get subsequent pages where as at the moment I am taking the last price returned and doing another query from then. 

Sorry if I'm getting confused and this is something different.

**Comment by rviney** [comment]
Good point, the prices API could also be updated to use the paging system, which is supported by V3 of `/prices/{epic}`:

http://labs.ig.com/rest-trading-api-reference/service-detail?id=521

I'll plan to do all three of these (activities, transactions, prices) in the one update.
